# Homework 4 - So many t-tests...

*Written by Bob Rehder*

T-tests are the most widely used statistical test in experimental research. But there is a whole "zoo" of t-tests: one-sample versus two, paired vs. independent, etc. You should know what t-test is appropriate in different situations, and how to run that t-test in Python. This is what this homework assignment asks you to do.

<div class="alert alert-danger" role="alert">
  Check the class schedule for information about homework due dates. 
</div>

As usual, first load the basic packages you'll need.

In [1]:
import numpy.random as npr
import numpy as np
import pandas as pd
import pingouin as pg

Imagine you have (somehow) gotten approval to assess the effects of Ritalin on cognitive performance of college students. You randomly assign 40 students in equal numbers to the "Ritalin" group (who are given Ritalin) and the "No Ritalin" group (who are given a placebo). Each student is then given a cognitive test that scores the student on a scale of 0-1. Below is some made-up data. (Please do not do this at home. Really.)

In [2]:
ritalin = np.array([78,85,82,86,77,80,82,80,79,85,76,80,82,84,84,68,81,83,84,78])
placebo = np.array([72,65,72,75,72,70,71,70,72,70,67,71,76,69,71,60,66,72,63,73])
df_ritalin = pd.DataFrame ({'Score': ritalin,'group': 'Ritalin'})
df_placebo = pd.DataFrame ({'Score': placebo,'group': 'Placebo'})
exp_df = pd.concat([df_ritalin,df_placebo])
exp_df['PID'] = range(1, len(exp_df) + 1)
exp_df

    Score    group  PID
0      78  Ritalin    1
1      85  Ritalin    2
2      82  Ritalin    3
3      86  Ritalin    4
4      77  Ritalin    5
5      80  Ritalin    6
6      82  Ritalin    7
7      80  Ritalin    8
8      79  Ritalin    9
9      85  Ritalin   10
10     76  Ritalin   11
11     80  Ritalin   12
12     82  Ritalin   13
13     84  Ritalin   14
14     84  Ritalin   15
15     68  Ritalin   16
16     81  Ritalin   17
17     83  Ritalin   18
18     84  Ritalin   19
19     78  Ritalin   20
0      72  Placebo   21
1      65  Placebo   22
2      72  Placebo   23
3      75  Placebo   24
4      72  Placebo   25
5      70  Placebo   26
6      71  Placebo   27
7      70  Placebo   28
8      72  Placebo   29
9      70  Placebo   30
10     67  Placebo   31
11     71  Placebo   32
12     76  Placebo   33
13     69  Placebo   34
14     71  Placebo   35
15     60  Placebo   36
16     66  Placebo   37
17     72  Placebo   38
18     63  Placebo   39
19     73  Placebo   40

Let's first look at the means of the two groups and whether they differ.

In [36]:
print("Mean of Ritalin group:", ritalin.mean())
print("Mean of Placebo group:", placebo.mean())
print("The difference in means is: ", ritalin.mean()-placebo.mean())

Mean of Ritalin group: 0.807
Mean of Placebo group: 0.6985000000000001
The difference in means is:  0.10849999999999993

So, the groups differ. But do they differ significantly?

<div class="alert alert-info" role="alert">
  <strong>Question 1A</strong> <br>
Please conduct a t-test to find out if the groups differ significantly. Assume the groups have equal variance and that we want to conduct a two-sided test.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here.  The code for your analysis should appear in the cells below.
</div>

<div class="alert alert-info" role="alert">
  <strong>Question 1B</strong> <br>
Write down how this result should appear in a report.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here.
</div>

<div class="alert alert-info" role="alert">
  <strong>Question 2A</strong> <br>
Please conduct a t-test that doesn't assume that the groups have equal variance.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here.  The code for your analysis should appear in the cells below.
</div>

<div class="alert alert-info" role="alert">
  <strong>Question 2B</strong> <br>
Write down how this result should appear in a report.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here.
</div>

The design above is called a "between subjects" design because each participant contributes one data point to one condition. Suppose the study was conducted as a "within subjects" (a.k.a. "repeated measures") design where every participant contributed data points to each condition. That is, supoose we had 20 participants instead of 40 participants and each of the 20 were tested both on and off Ritalin. We can continue to use the same made-up data from the previous questions. It's just that we now know that the data comes from testing 20 participants twice rather than from testing 40 participants once.

In [3]:
exp_df = pd.DataFrame ({'Ritalin_Score': ritalin, 'Placebo_Score': placebo})
exp_df['PID'] = range(1, len(exp_df) + 1)
exp_df

    Ritalin_Score  Placebo_Score  PID
0              78             72    1
1              85             65    2
2              82             72    3
3              86             75    4
4              77             72    5
5              80             70    6
6              82             71    7
7              80             70    8
8              79             72    9
9              85             70   10
10             76             67   11
11             80             71   12
12             82             76   13
13             84             69   14
14             84             71   15
15             68             60   16
16             81             66   17
17             83             72   18
18             84             63   19
19             78             73   20

<div class="alert alert-info" role="alert">
  <strong>Question 3A</strong> <br>
Please conduct a t-test to find out if the two conditions differ. Continue to assume that we want a two-sided test.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here.  The code for your analysis should appear in the cells below.
</div>

<div class="alert alert-info" role="alert">
  <strong>Question 3B</strong> <br>
Write down how this result should appear in a report.
</div>

<div class="alert alert-warning" role="alert">
  <strong>Your Answer</strong> <br>
  Delete this text and put your answer here. 
</div>

Be aware that there are pros and cons to within-subject designs. One pro is that they tend to be statistically more powerful. One con is that they usually introduce potential "order effects." For example, if our participants are taking the cognitive test twice (once on, once off Ritalin) could it be that they'll do better the second time they take it (independently of whether they are on Ritalin or not)? Thus, it would be typical introduce a "counterbalancing" factor that controlled for that: Have half the participants take Ritalin first then the placebo and then reverse that order for the other half. The hope would be that any effect of taking the cognitive test first or last would then get averaged out over subjects. But this is a research design question best left for another time.

To turn in your homework, follow the following steps:

1. Export the notebook to an HTML file
2. Open the HTML file in a browser
3. Print/export the HTML file as a PDF
4. Submit the PDF on Gradescope

Please reach out to the instructor if you have any problems.